"""
Comprehensive International Emergency Numbers & Helplines Database
Covers 150+ sovereign nations and territories with verified national helplines,
fire departments, police dispatch, and medical ambulances.
"""

EMERGENCY_NUMBERS = {
    # ── North America ──
    "US": {"country": "United States", "helpline": "911", "fire": "911", "police": "911", "ambulance": "911", "fire_name": "Fire Department", "police_name": "Police Dispatch (911)", "flag": "🇺🇸"},
    "CA": {"country": "Canada", "helpline": "911", "fire": "911", "police": "911", "ambulance": "911", "fire_name": "Fire & Rescue", "police_name": "Police Dispatch (911)", "flag": "🇨🇦"},
    "MX": {"country": "Mexico", "helpline": "911", "fire": "911", "police": "911", "ambulance": "911", "fire_name": "Bomberos (911)", "police_name": "Policía (911)", "flag": "🇲🇽"},
    "GL": {"country": "Greenland", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Fire Service (112)", "police_name": "Police (112)", "flag": "🇬🇱"},
    "BM": {"country": "Bermuda", "helpline": "911", "fire": "911", "police": "911", "ambulance": "911", "fire_name": "Fire & Rescue (911)", "police_name": "Police (911)", "flag": "🇧🇲"},

    # ── Central America & Caribbean ──
    "GT": {"country": "Guatemala", "helpline": "123", "fire": "123", "police": "110", "ambulance": "128", "fire_name": "Bomberos (123)", "police_name": "PNC Policía (110)", "flag": "🇬🇹"},
    "BZ": {"country": "Belize", "helpline": "911", "fire": "990", "police": "911", "ambulance": "90", "fire_name": "National Fire Service (990)", "police_name": "Police (911)", "flag": "🇧🇿"},
    "SV": {"country": "El Salvador", "helpline": "911", "fire": "913", "police": "911", "ambulance": "132", "fire_name": "Bomberos (913)", "police_name": "PNC Policía (911)", "flag": "🇸🇻"},
    "HN": {"country": "Honduras", "helpline": "911", "fire": "198", "police": "911", "ambulance": "195", "fire_name": "Bomberos (198)", "police_name": "Policía (911)", "flag": "🇭🇳"},
    "NI": {"country": "Nicaragua", "helpline": "118", "fire": "115", "police": "118", "ambulance": "128", "fire_name": "Bomberos (115)", "police_name": "Policía (118)", "flag": "🇳🇮"},
    "CR": {"country": "Costa Rica", "helpline": "911", "fire": "118", "police": "911", "ambulance": "128", "fire_name": "Bomberos (118)", "police_name": "Fuerza Pública (911)", "flag": "🇨🇷"},
    "PA": {"country": "Panama", "helpline": "911", "fire": "103", "police": "104", "ambulance": "911", "fire_name": "Bomberos (103)", "police_name": "Policía Nacional (104)", "flag": "🇵🇦"},
    "CU": {"country": "Cuba", "helpline": "106", "fire": "105", "police": "106", "ambulance": "104", "fire_name": "Bomberos (105)", "police_name": "Policía (106)", "flag": "🇨🇺"},
    "JM": {"country": "Jamaica", "helpline": "119", "fire": "110", "police": "119", "ambulance": "110", "fire_name": "Fire Brigade (110)", "police_name": "Police (119)", "flag": "🇯🇲"},
    "HT": {"country": "Haiti", "helpline": "114", "fire": "115", "police": "114", "ambulance": "116", "fire_name": "Sapeurs-Pompiers (115)", "police_name": "Police Nationale (114)", "flag": "🇭🇹"},
    "DO": {"country": "Dominican Republic", "helpline": "911", "fire": "911", "police": "911", "ambulance": "911", "fire_name": "Bomberos (911)", "police_name": "Policía Nacional (911)", "flag": "🇩🇴"},
    "BS": {"country": "Bahamas", "helpline": "911", "fire": "919", "police": "911", "ambulance": "919", "fire_name": "Fire Services (919)", "police_name": "Royal Police (911)", "flag": "🇧🇸"},
    "TT": {"country": "Trinidad and Tobago", "helpline": "999", "fire": "990", "police": "999", "ambulance": "811", "fire_name": "Fire Service (990)", "police_name": "Police (999)", "flag": "🇹🇹"},
    "BB": {"country": "Barbados", "helpline": "211", "fire": "311", "police": "211", "ambulance": "511", "fire_name": "Fire Service (311)", "police_name": "Police (211)", "flag": "🇧🇧"},

    # ── South America ──
    "BR": {"country": "Brazil", "helpline": "190", "fire": "193", "police": "190", "ambulance": "192", "fire_name": "Corpo de Bombeiros (193)", "police_name": "Polícia Militar (190)", "flag": "🇧🇷"},
    "AR": {"country": "Argentina", "helpline": "911", "fire": "100", "police": "911", "ambulance": "107", "fire_name": "Bomberos (100)", "police_name": "Policía (911)", "flag": "🇦🇷"},
    "CL": {"country": "Chile", "helpline": "133", "fire": "132", "police": "133", "ambulance": "131", "fire_name": "Bomberos (132)", "police_name": "Carabineros (133)", "flag": "🇨🇱"},
    "CO": {"country": "Colombia", "helpline": "123", "fire": "119", "police": "123", "ambulance": "125", "fire_name": "Bomberos (119)", "police_name": "Policía Nacional (123)", "flag": "🇨🇴"},
    "PE": {"country": "Peru", "helpline": "105", "fire": "116", "police": "105", "ambulance": "106", "fire_name": "Bomberos (116)", "police_name": "Policía Nacional (105)", "flag": "🇵🇪"},
    "VE": {"country": "Venezuela", "helpline": "911", "fire": "171", "police": "911", "ambulance": "171", "fire_name": "Bomberos (171)", "police_name": "Policía (911)", "flag": "🇻🇪"},
    "EC": {"country": "Ecuador", "helpline": "911", "fire": "911", "police": "911", "ambulance": "911", "fire_name": "Bomberos (911)", "police_name": "Policía (911)", "flag": "🇪🇨"},
    "BO": {"country": "Bolivia", "helpline": "911", "fire": "119", "police": "110", "ambulance": "118", "fire_name": "Bomberos (119)", "police_name": "Policía Boliviana (110)", "flag": "🇧🇴"},
    "PY": {"country": "Paraguay", "helpline": "911", "fire": "132", "police": "911", "ambulance": "141", "fire_name": "Bomberos (132)", "police_name": "Policía Nacional (911)", "flag": "🇵🇾"},
    "UY": {"country": "Uruguay", "helpline": "911", "fire": "104", "police": "911", "ambulance": "105", "fire_name": "Bomberos (104)", "police_name": "Policía (911)", "flag": "🇺🇾"},
    "GY": {"country": "Guyana", "helpline": "911", "fire": "912", "police": "911", "ambulance": "913", "fire_name": "Fire Service (912)", "police_name": "Police Force (911)", "flag": "🇬🇾"},
    "SR": {"country": "Suriname", "helpline": "115", "fire": "110", "police": "115", "ambulance": "113", "fire_name": "Brandweer Fire (110)", "police_name": "Politie (115)", "flag": "🇸🇷"},

    # ── Europe - Western & Northern ──
    "GB": {"country": "United Kingdom", "helpline": "999", "fire": "999", "police": "999", "ambulance": "999", "fire_name": "Fire & Rescue (999)", "police_name": "Police Dispatch (999)", "flag": "🇬🇧"},
    "IE": {"country": "Ireland", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Fire Service (112)", "police_name": "Garda (112)", "flag": "🇮🇪"},
    "FR": {"country": "France", "helpline": "112", "fire": "18", "police": "17", "ambulance": "15", "fire_name": "Sapeurs-Pompiers (18)", "police_name": "Police Nationale (17)", "flag": "🇫🇷"},
    "DE": {"country": "Germany", "helpline": "112", "fire": "112", "police": "110", "ambulance": "112", "fire_name": "Feuerwehr (112)", "police_name": "Polizei (110)", "flag": "🇩🇪"},
    "IT": {"country": "Italy", "helpline": "112", "fire": "115", "police": "112", "ambulance": "118", "fire_name": "Vigili del Fuoco (115)", "police_name": "Carabinieri / Polizia (112)", "flag": "🇮🇹"},
    "ES": {"country": "Spain", "helpline": "112", "fire": "080", "police": "091", "ambulance": "061", "fire_name": "Bomberos (080)", "police_name": "Policía Nacional (091)", "flag": "🇪🇸"},
    "PT": {"country": "Portugal", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Bombeiros (112)", "police_name": "Polícia (112)", "flag": "🇵🇹"},
    "NL": {"country": "Netherlands", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Brandweer (112)", "police_name": "Politie (112)", "flag": "🇳🇱"},
    "BE": {"country": "Belgium", "helpline": "112", "fire": "112", "police": "101", "ambulance": "112", "fire_name": "Brandweer / Pompiers (112)", "police_name": "Police (101)", "flag": "🇧🇪"},
    "LU": {"country": "Luxembourg", "helpline": "112", "fire": "112", "police": "113", "ambulance": "112", "fire_name": "CGDIS Fire & Rescue (112)", "police_name": "Police Grand-Ducale (113)", "flag": "🇱🇺"},
    "CH": {"country": "Switzerland", "helpline": "112", "fire": "118", "police": "117", "ambulance": "144", "fire_name": "Feuerwehr / Pompiers (118)", "police_name": "Polizei / Police (117)", "flag": "🇨🇭"},
    "AT": {"country": "Austria", "helpline": "112", "fire": "122", "police": "133", "ambulance": "144", "fire_name": "Feuerwehr (122)", "police_name": "Polizei (133)", "flag": "🇦🇹"},
    "SE": {"country": "Sweden", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Räddningstjänst (112)", "police_name": "Polisen (112)", "flag": "🇸🇪"},
    "NO": {"country": "Norway", "helpline": "112", "fire": "110", "police": "112", "ambulance": "113", "fire_name": "Brannvesen (110)", "police_name": "Politi (112)", "flag": "🇳🇴"},
    "DK": {"country": "Denmark", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Brandvæsen (112)", "police_name": "Politi (112)", "flag": "🇩🇰"},
    "FI": {"country": "Finland", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Pelastuslaitos (112)", "police_name": "Poliisi (112)", "flag": "🇫🇮"},
    "IS": {"country": "Iceland", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Slökkvilið (112)", "police_name": "Lögreglan (112)", "flag": "🇮🇸"},

    # ── Europe - Central, Eastern & Southern ──
    "UA": {"country": "Ukraine", "helpline": "112", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "State Emergency Service (101)", "police_name": "National Police (102)", "flag": "🇺🇦"},
    "RU": {"country": "Russia", "helpline": "112", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "EMERCOM Fire Rescue (101)", "police_name": "Police (102)", "flag": "🇷🇺"},
    "PL": {"country": "Poland", "helpline": "112", "fire": "998", "police": "997", "ambulance": "999", "fire_name": "Straż Pożarna (998)", "police_name": "Policja (997)", "flag": "🇵🇱"},
    "CZ": {"country": "Czech Republic", "helpline": "112", "fire": "150", "police": "158", "ambulance": "155", "fire_name": "Hasiči (150)", "police_name": "Policie (158)", "flag": "🇨🇿"},
    "SK": {"country": "Slovakia", "helpline": "112", "fire": "150", "police": "158", "ambulance": "155", "fire_name": "Hasiči (150)", "police_name": "Polícia (158)", "flag": "🇸🇰"},
    "HU": {"country": "Hungary", "helpline": "112", "fire": "105", "police": "107", "ambulance": "104", "fire_name": "Katasztrófavédelem (105)", "police_name": "Rendőrség (107)", "flag": "🇭🇺"},
    "RO": {"country": "Romania", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Pompieri (112)", "police_name": "Poliția (112)", "flag": "🇷🇴"},
    "BG": {"country": "Bulgaria", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Fire Safety (112)", "police_name": "Police (112)", "flag": "🇧🇬"},
    "GR": {"country": "Greece", "helpline": "112", "fire": "199", "police": "100", "ambulance": "166", "fire_name": "Hellenic Fire Service (199)", "police_name": "Hellenic Police (100)", "flag": "🇬🇷"},
    "CY": {"country": "Cyprus", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Fire Service (112)", "police_name": "Cyprus Police (112)", "flag": "🇨🇾"},
    "HR": {"country": "Croatia", "helpline": "112", "fire": "193", "police": "192", "ambulance": "194", "fire_name": "Vatrogasci (193)", "police_name": "Policija (192)", "flag": "🇭🇷"},
    "SI": {"country": "Slovenia", "helpline": "112", "fire": "112", "police": "113", "ambulance": "112", "fire_name": "Gasilci (112)", "police_name": "Policija (113)", "flag": "🇸🇮"},
    "RS": {"country": "Serbia", "helpline": "112", "fire": "193", "police": "192", "ambulance": "194", "fire_name": "Vatrogasci (193)", "police_name": "Policija (192)", "flag": "🇷🇸"},
    "BA": {"country": "Bosnia and Herzegovina", "helpline": "112", "fire": "123", "police": "122", "ambulance": "124", "fire_name": "Vatrogasci (123)", "police_name": "Policija (122)", "flag": "🇧🇦"},
    "ME": {"country": "Montenegro", "helpline": "112", "fire": "123", "police": "122", "ambulance": "124", "fire_name": "Vatrogasci (123)", "police_name": "Policija (122)", "flag": "🇲🇪"},
    "MK": {"country": "North Macedonia", "helpline": "112", "fire": "193", "police": "192", "ambulance": "194", "fire_name": "Protivpožarna (193)", "police_name": "Policija (192)", "flag": "🇲🇰"},
    "AL": {"country": "Albania", "helpline": "112", "fire": "128", "police": "129", "ambulance": "127", "fire_name": "Zjarrfikësit (128)", "police_name": "Policia (129)", "flag": "🇦🇱"},
    "EE": {"country": "Estonia", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Päästeamet (112)", "police_name": "Politsei (112)", "flag": "🇪🇪"},
    "LV": {"country": "Latvia", "helpline": "112", "fire": "112", "police": "110", "ambulance": "113", "fire_name": "VUGD Fire (112)", "police_name": "Policija (110)", "flag": "🇱🇻"},
    "LT": {"country": "Lithuania", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Gaisrinė (112)", "police_name": "Policija (112)", "flag": "🇱🇹"},
    "BY": {"country": "Belarus", "helpline": "112", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "Rescue Ministry (101)", "police_name": "Militsiya (102)", "flag": "🇧🇾"},
    "MD": {"country": "Moldova", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Salvatori și Pompieri (112)", "police_name": "Poliția (112)", "flag": "🇲🇩"},
    "GE": {"country": "Georgia", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Emergency Service (112)", "police_name": "Patrol Police (112)", "flag": "🇬🇪"},
    "AM": {"country": "Armenia", "helpline": "911", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "Rescue Service (101)", "police_name": "Police (102)", "flag": "🇦🇲"},
    "AZ": {"country": "Azerbaijan", "helpline": "112", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "FHN Fire (101)", "police_name": "Police (102)", "flag": "🇦🇿"},

    # ── Asia - South Asia ──
    "IN": {"country": "India", "helpline": "112", "fire": "101", "police": "100", "ambulance": "108", "fire_name": "Fire Brigade (101)", "police_name": "Police Control Room (100)", "flag": "🇮🇳"},
    "PK": {"country": "Pakistan", "helpline": "15", "fire": "16", "police": "15", "ambulance": "1122", "fire_name": "Fire Brigade (16)", "police_name": "Police Emergency (15)", "flag": "🇵🇰"},
    "BD": {"country": "Bangladesh", "helpline": "999", "fire": "199", "police": "999", "ambulance": "199", "fire_name": "Fire Service (199)", "police_name": "Bangladesh Police (999)", "flag": "🇧🇩"},
    "NP": {"country": "Nepal", "helpline": "112", "fire": "101", "police": "100", "ambulance": "102", "fire_name": "Fire Brigade (101)", "police_name": "Nepal Police (100)", "flag": "🇳🇵"},
    "LK": {"country": "Sri Lanka", "helpline": "119", "fire": "110", "police": "119", "ambulance": "1990", "fire_name": "Fire Brigade (110)", "police_name": "Police Emergency (119)", "flag": "🇱🇰"},
    "BT": {"country": "Bhutan", "helpline": "112", "fire": "110", "police": "113", "ambulance": "112", "fire_name": "Fire Division (110)", "police_name": "Royal Bhutan Police (113)", "flag": "🇧🇹"},
    "MV": {"country": "Maldives", "helpline": "119", "fire": "118", "police": "119", "ambulance": "102", "fire_name": "MNDF Fire (118)", "police_name": "Police Service (119)", "flag": "🇲🇻"},
    "AF": {"country": "Afghanistan", "helpline": "119", "fire": "119", "police": "119", "ambulance": "112", "fire_name": "Fire Service (119)", "police_name": "Police (119)", "flag": "🇦🇫"},

    # ── Asia - East & Central ──
    "CN": {"country": "China", "helpline": "110", "fire": "119", "police": "110", "ambulance": "120", "fire_name": "Fire Service (119)", "police_name": "Public Security Police (110)", "flag": "🇨🇳"},
    "JP": {"country": "Japan", "helpline": "110", "fire": "119", "police": "110", "ambulance": "119", "fire_name": "Fire & Disaster Agency (119)", "police_name": "Police (110)", "flag": "🇯🇵"},
    "KR": {"country": "South Korea", "helpline": "119", "fire": "119", "police": "112", "ambulance": "119", "fire_name": "National Fire Agency (119)", "police_name": "Police (112)", "flag": "🇰🇷"},
    "KP": {"country": "North Korea", "helpline": "119", "fire": "119", "police": "110", "ambulance": "119", "fire_name": "Fire Command (119)", "police_name": "Security (110)", "flag": "🇰🇵"},
    "TW": {"country": "Taiwan", "helpline": "110", "fire": "119", "police": "110", "ambulance": "119", "fire_name": "National Fire Agency (119)", "police_name": "Police (110)", "flag": "🇹🇼"},
    "MN": {"country": "Mongolia", "helpline": "105", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "Emergency Management (101)", "police_name": "Police (102)", "flag": "🇲🇳"},
    "KZ": {"country": "Kazakhstan", "helpline": "112", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "Emergency Committee (101)", "police_name": "Police (102)", "flag": "🇰🇿"},
    "UZ": {"country": "Uzbekistan", "helpline": "112", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "Fire Safety (101)", "police_name": "Police (102)", "flag": "🇺🇿"},
    "TM": {"country": "Turkmenistan", "helpline": "112", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "Fire Service (101)", "police_name": "Police (102)", "flag": "🇹🇲"},
    "KG": {"country": "Kyrgyzstan", "helpline": "112", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "Fire Service (101)", "police_name": "Police (102)", "flag": "🇰🇬"},
    "TJ": {"country": "Tajikistan", "helpline": "112", "fire": "101", "police": "102", "ambulance": "103", "fire_name": "Fire Department (101)", "police_name": "Police (102)", "flag": "🇹🇯"},

    # ── Asia - Southeast ──
    "SG": {"country": "Singapore", "helpline": "995", "fire": "995", "police": "999", "ambulance": "995", "fire_name": "SCDF Emergency Fire (995)", "police_name": "Police Operations (999)", "flag": "🇸🇬"},
    "MY": {"country": "Malaysia", "helpline": "999", "fire": "994", "police": "999", "ambulance": "999", "fire_name": "Bomba Fire & Rescue (994)", "police_name": "Royal Malaysia Police (999)", "flag": "🇲🇾"},
    "ID": {"country": "Indonesia", "helpline": "112", "fire": "113", "police": "110", "ambulance": "118", "fire_name": "Damkar Fire Rescue (113)", "police_name": "POLRI Police (110)", "flag": "🇮🇩"},
    "TH": {"country": "Thailand", "helpline": "191", "fire": "199", "police": "191", "ambulance": "1669", "fire_name": "Fire & Rescue (199)", "police_name": "Royal Thai Police (191)", "flag": "🇹🇭"},
    "VN": {"country": "Vietnam", "helpline": "114", "fire": "114", "police": "113", "ambulance": "115", "fire_name": "Fire & Rescue Police (114)", "police_name": "Police (113)", "flag": "🇻🇳"},
    "PH": {"country": "Philippines", "helpline": "911", "fire": "911", "police": "911", "ambulance": "911", "fire_name": "Bureau of Fire Protection (911)", "police_name": "PNP Police (911)", "flag": "🇵🇭"},
    "MM": {"country": "Myanmar", "helpline": "199", "fire": "191", "police": "199", "ambulance": "192", "fire_name": "Fire Services (191)", "police_name": "Police (199)", "flag": "🇲🇲"},
    "KH": {"country": "Cambodia", "helpline": "117", "fire": "118", "police": "117", "ambulance": "119", "fire_name": "Fire Brigade (118)", "police_name": "Police (117)", "flag": "🇰🇭"},
    "LA": {"country": "Laos", "helpline": "1191", "fire": "1190", "police": "1191", "ambulance": "1195", "fire_name": "Fire Rescue (1190)", "police_name": "Police (1191)", "flag": "🇱🇦"},
    "BN": {"country": "Brunei", "helpline": "993", "fire": "995", "police": "993", "ambulance": "991", "fire_name": "Fire & Rescue (995)", "police_name": "Royal Police (993)", "flag": "🇧🇳"},
    "TL": {"country": "Timor-Leste", "helpline": "112", "fire": "115", "police": "112", "ambulance": "110", "fire_name": "Bombeiros (115)", "police_name": "PNTL Police (112)", "flag": "🇹🇱"},

    # ── Middle East ──
    "TR": {"country": "Turkey", "helpline": "112", "fire": "110", "police": "155", "ambulance": "112", "fire_name": "İtfaiye (110)", "police_name": "Polis (155)", "flag": "🇹🇷"},
    "SA": {"country": "Saudi Arabia", "helpline": "911", "fire": "998", "police": "999", "ambulance": "997", "fire_name": "Civil Defense Fire (998)", "police_name": "Police (999)", "flag": "🇸🇦"},
    "AE": {"country": "United Arab Emirates", "helpline": "999", "fire": "997", "police": "999", "ambulance": "998", "fire_name": "Civil Defence (997)", "police_name": "Police (999)", "flag": "🇦🇪"},
    "IL": {"country": "Israel", "helpline": "100", "fire": "102", "police": "100", "ambulance": "101", "fire_name": "Fire & Rescue (102)", "police_name": "Police (100)", "flag": "🇮🇱"},
    "PS": {"country": "Palestine", "helpline": "100", "fire": "102", "police": "100", "ambulance": "101", "fire_name": "Civil Defense (102)", "police_name": "Police (100)", "flag": "🇵🇸"},
    "IQ": {"country": "Iraq", "helpline": "112", "fire": "115", "police": "104", "ambulance": "122", "fire_name": "Civil Defense Fire (115)", "police_name": "Police Control (104)", "flag": "🇮🇶"},
    "IR": {"country": "Iran", "helpline": "110", "fire": "125", "police": "110", "ambulance": "115", "fire_name": "Atashneshani Fire (125)", "police_name": "Police (110)", "flag": "🇮🇷"},
    "JO": {"country": "Jordan", "helpline": "911", "fire": "911", "police": "911", "ambulance": "911", "fire_name": "Civil Defense (911)", "police_name": "Public Security (911)", "flag": "🇯🇴"},
    "LB": {"country": "Lebanon", "helpline": "112", "fire": "175", "police": "112", "ambulance": "140", "fire_name": "Fire Brigade (175)", "police_name": "ISF Police (112)", "flag": "🇱🇧"},
    "SY": {"country": "Syria", "helpline": "112", "fire": "113", "police": "112", "ambulance": "110", "fire_name": "Fire Brigade (113)", "police_name": "Police (112)", "flag": "🇸🇾"},
    "KW": {"country": "Kuwait", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Fire Force (112)", "police_name": "Police (112)", "flag": "🇰🇼"},
    "QA": {"country": "Qatar", "helpline": "999", "fire": "999", "police": "999", "ambulance": "999", "fire_name": "Civil Defence (999)", "police_name": "Police (999)", "flag": "🇶🇦"},
    "BH": {"country": "Bahrain", "helpline": "999", "fire": "999", "police": "999", "ambulance": "999", "fire_name": "Civil Defence (999)", "police_name": "Police (999)", "flag": "🇧🇭"},
    "OM": {"country": "Oman", "helpline": "9999", "fire": "9999", "police": "9999", "ambulance": "9999", "fire_name": "Civil Defence (9999)", "police_name": "Royal Oman Police (9999)", "flag": "🇴🇲"},
    "YE": {"country": "Yemen", "helpline": "199", "fire": "191", "police": "199", "ambulance": "191", "fire_name": "Civil Defense (191)", "police_name": "Police (199)", "flag": "🇾🇪"},

    # ── Africa - Northern ──
    "EG": {"country": "Egypt", "helpline": "122", "fire": "180", "police": "122", "ambulance": "123", "fire_name": "Civil Protection Fire (180)", "police_name": "Police (122)", "flag": "🇪🇬"},
    "DZ": {"country": "Algeria", "helpline": "17", "fire": "14", "police": "17", "ambulance": "14", "fire_name": "Protection Civile (14)", "police_name": "Sûreté Nationale (17)", "flag": "🇩🇿"},
    "MA": {"country": "Morocco", "helpline": "19", "fire": "15", "police": "19", "ambulance": "15", "fire_name": "Protection Civile (15)", "police_name": "Police (19)", "flag": "🇲🇦"},
    "TN": {"country": "Tunisia", "helpline": "197", "fire": "198", "police": "197", "ambulance": "190", "fire_name": "Protection Civile (198)", "police_name": "Police Secours (197)", "flag": "🇹🇳"},
    "LY": {"country": "Libya", "helpline": "1515", "fire": "1515", "police": "1515", "ambulance": "1515", "fire_name": "National Safety (1515)", "police_name": "Police (1515)", "flag": "🇱🇾"},
    "SD": {"country": "Sudan", "helpline": "999", "fire": "998", "police": "999", "ambulance": "998", "fire_name": "Civil Defense (998)", "police_name": "Police (999)", "flag": "🇸🇩"},

    # ── Africa - Sub-Saharan & Southern ──
    "ZA": {"country": "South Africa", "helpline": "112", "fire": "10177", "police": "10111", "ambulance": "10177", "fire_name": "Fire & Rescue (10177)", "police_name": "SAPS Police (10111)", "flag": "🇿🇦"},
    "NG": {"country": "Nigeria", "helpline": "112", "fire": "112", "police": "112", "ambulance": "112", "fire_name": "Federal Fire Service (112)", "police_name": "Police Force (112)", "flag": "🇳🇬"},
    "KE": {"country": "Kenya", "helpline": "999", "fire": "999", "police": "999", "ambulance": "999", "fire_name": "Fire & Rescue (999)", "police_name": "National Police (999)", "flag": "🇰🇪"},
    "ET": {"country": "Ethiopia", "helpline": "911", "fire": "939", "police": "991", "ambulance": "907", "fire_name": "Fire & Disaster Agency (939)", "police_name": "Federal Police (991)", "flag": "🇪🇹"},
    "GH": {"country": "Ghana", "helpline": "112", "fire": "192", "police": "191", "ambulance": "193", "fire_name": "National Fire Service (192)", "police_name": "Ghana Police (191)", "flag": "🇬🇭"},
    "CI": {"country": "Ivory Coast", "helpline": "111", "fire": "180", "police": "170", "ambulance": "185", "fire_name": "Sapeurs-Pompiers (180)", "police_name": "Police (170)", "flag": "🇨🇮"},
    "SN": {"country": "Senegal", "helpline": "17", "fire": "18", "police": "17", "ambulance": "15", "fire_name": "Sapeurs-Pompiers (18)", "police_name": "Police (17)", "flag": "🇸🇳"},
    "TZ": {"country": "Tanzania", "helpline": "112", "fire": "114", "police": "112", "ambulance": "115", "fire_name": "Fire & Rescue (114)", "police_name": "Police Force (112)", "flag": "🇹🇿"},
    "UG": {"country": "Uganda", "helpline": "112", "fire": "112", "police": "999", "ambulance": "911", "fire_name": "Fire Brigade (112)", "police_name": "Police (999)", "flag": "🇺🇬"},
    "RW": {"country": "Rwanda", "helpline": "112", "fire": "111", "police": "112", "ambulance": "912", "fire_name": "Fire & Rescue Brigade (111)", "police_name": "National Police (112)", "flag": "🇷🇼"},
    "CM": {"country": "Cameroon", "helpline": "112", "fire": "118", "police": "117", "ambulance": "119", "fire_name": "Sapeurs-Pompiers (118)", "police_name": "Police (117)", "flag": "🇨🇲"},
    "AO": {"country": "Angola", "helpline": "112", "fire": "115", "police": "113", "ambulance": "112", "fire_name": "Bombeiros (115)", "police_name": "Polícia Nacional (113)", "flag": "🇦🇴"},
    "CD": {"country": "DR Congo", "helpline": "112", "fire": "118", "police": "112", "ambulance": "118", "fire_name": "Sapeurs-Pompiers (118)", "police_name": "Police (112)", "flag": "🇨🇩"},
    "CG": {"country": "Republic of Congo", "helpline": "112", "fire": "118", "police": "117", "ambulance": "118", "fire_name": "Pompiers (118)", "police_name": "Police (117)", "flag": "🇨🇬"},
    "GA": {"country": "Gabon", "helpline": "177", "fire": "18", "police": "177", "ambulance": "1300", "fire_name": "Sapeurs-Pompiers (18)", "police_name": "Police (177)", "flag": "🇬🇦"},
    "ZM": {"country": "Zambia", "helpline": "999", "fire": "993", "police": "991", "ambulance": "992", "fire_name": "Fire Brigade (993)", "police_name": "Police (991)", "flag": "🇿🇲"},
    "ZW": {"country": "Zimbabwe", "helpline": "999", "fire": "993", "police": "995", "ambulance": "994", "fire_name": "Fire Brigade (993)", "police_name": "Police (995)", "flag": "🇿🇼"},
    "MZ": {"country": "Mozambique", "helpline": "112", "fire": "198", "police": "112", "ambulance": "117", "fire_name": "Bombeiros (198)", "police_name": "Polícia (112)", "flag": "🇲🇿"},
    "BW": {"country": "Botswana", "helpline": "911", "fire": "998", "police": "999", "ambulance": "997", "fire_name": "Fire Service (998)", "police_name": "Police (999)", "flag": "🇧🇼"},
    "NA": {"country": "Namibia", "helpline": "112", "fire": "2032276", "police": "10111", "ambulance": "2032276", "fire_name": "Fire Brigade", "police_name": "Police (10111)", "flag": "🇳🇦"},
    "MG": {"country": "Madagascar", "helpline": "117", "fire": "118", "police": "117", "ambulance": "124", "fire_name": "Sapeurs-Pompiers (118)", "police_name": "Police (117)", "flag": "🇲🇬"},
    "MU": {"country": "Mauritius", "helpline": "112", "fire": "115", "police": "999", "ambulance": "114", "fire_name": "Fire Service (115)", "police_name": "Police (999)", "flag": "🇲🇺"},

    # ── Oceania ──
    "AU": {"country": "Australia", "helpline": "000", "fire": "000", "police": "000", "ambulance": "000", "fire_name": "Fire & Rescue (000)", "police_name": "Police (000)", "flag": "🇦🇺"},
    "NZ": {"country": "New Zealand", "helpline": "111", "fire": "111", "police": "111", "ambulance": "111", "fire_name": "Fire and Emergency (111)", "police_name": "Police (111)", "flag": "🇳🇿"},
    "PG": {"country": "Papua New Guinea", "helpline": "112", "fire": "110", "police": "112", "ambulance": "111", "fire_name": "Fire Service (110)", "police_name": "Police (112)", "flag": "🇵🇬"},
    "FJ": {"country": "Fiji", "helpline": "911", "fire": "910", "police": "917", "ambulance": "911", "fire_name": "National Fire Authority (910)", "police_name": "Police (917)", "flag": "🇫🇯"},
    "WS": {"country": "Samoa", "helpline": "999", "fire": "994", "police": "995", "ambulance": "996", "fire_name": "Fire & Emergency (994)", "police_name": "Police (995)", "flag": "🇼🇸"},
    "TO": {"country": "Tonga", "helpline": "911", "fire": "999", "police": "922", "ambulance": "933", "fire_name": "Fire Services (999)", "police_name": "Police (922)", "flag": "🇹🇴"},
    "VU": {"country": "Vanuatu", "helpline": "112", "fire": "113", "police": "111", "ambulance": "112", "fire_name": "Fire Service (113)", "police_name": "Police (111)", "flag": "🇻🇺"},
    "SB": {"country": "Solomon Islands", "helpline": "999", "fire": "988", "police": "999", "ambulance": "911", "fire_name": "Fire Service (988)", "police_name": "Police (999)", "flag": "🇸🇧"}
}

DEFAULT_EMERGENCY = {
    "country": "International",
    "helpline": "112",
    "fire": "112",
    "police": "911",
    "ambulance": "112",
    "fire_name": "Fire Emergency (112)",
    "police_name": "Police Dispatch (911)",
    "flag": "🌐"
}
